postgresql:
  volumePermissions:
    enabled: true
  global:
    postgresql:
      auth:
        username: "airflow"
        database: "airflow"
        existingSecret: "airflow-postgresql-credentials"

airflow:
  enabled: true
  executor: "KubernetesExecutor"
  postgresql:
    enabled: false
  workers:
    replicas: 0
  redis:
    enabled: false
  data:
    metadataSecretName: "airflow-credentials"
  apiServer:
    resources:
      requests:
        cpu: "2"
        memory: "2Gi"
      limits:
        cpu: "4"
        memory: "4Gi"
    startupProbe:
      failureThreshold: 20
      periodSeconds: 10
  scheduler:
    startupProbe:
      failureThreshold: 20
      periodSeconds: 10
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "2Gi"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
  config:
    core:
      load_examples: "False"
  migrateDatabaseJob:
    useHelmHooks: false
    applyCustomEnv: false
    jobAnnotations:
      "argocd.argoproj.io/hook": Sync
  createUserJob:
    useHelmHooks: false
    applyCustomEnv: false
  dags:
    gitSync:
      enabled: true
      repo: "https://github.com/conexasaude/airflow.git"
      branch: "homologacao"
      rev: "HEAD"
      depth: 1
      wait: 60
      maxFailures: 3
      subPath: "dags_eks"
      credentialsSecret: "airflow-credentials"
  dagProcessor:
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "2Gi"